#!/bin/env perl
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2021 Eric Herman <eric@freesa.org>
# Copyright (C) 2021 Keith Reynolds <keithr@pwcrypt.keithr.com>
use strict;
use warnings;

my $pwtype = 'faux-password';
my $salt   = '9bNjt4P8TLP6IWL1';
my $pw     = 'foo';
my $hash =
'$6$9bNjt4P8TLP6IWL1$pwlTVnveoApfAlgLE5N0drY5Ujx8yCcV3vay0/clcSqP6Ft5Idd0sfO30Q/aZhPhSXt8gqY4uCjaIiBiV61Vo0';

my $output = `tests/expect-no-confirm.sh $pwtype sha512 $salt $pw`;

my $prompt = "$pwtype passphrase: ";
die "prompt '$prompt' missing" unless ( $output =~ "$prompt" );

die "passphrase found in output" if ( $output =~ $pw );

# assert that the hash is the last line of the output

my @lines     = split( /[\r\n]/, $output );
my $last_line = $lines[-1];
die "hash not matched" unless ( $last_line eq $hash );
